# -*- mode: yaml-*-
# vi: set ft=yaml sw=2 ts=2 :

- name: Prepare application server
  hosts: node
  sudo: True
  vars:
    project_dir: /opt/project/
  tasks:
    - name: set locale
      lineinfile: dest=/etc/default/locale line="LC_ALL=C"

    - name: install curl
      apt: name={{ item }} update_cache=yes
      with_items:
        - git
        - curl
        - postgresql 
        - postgresql-contrib
        - libpq-dev
        - python-dev
        - python-psycopg2
        - docker
        - nginx

    - name: install pip
      shell: curl https://bootstrap.pypa.io/get-pip.py | python -

    - pip: name=virtualenv

    - name: Install docker-py
      pip: name=docker-py version=1.1.0

    - pip: requirements={{project_dir}}requirements.pip virtualenv=/ENV

    - name: add node ppa
      shell: curl -sL https://deb.nodesource.com/setup | bash -

    - name: install node and npm
      apt: name=nodejs update_cache=yes

    - name: install redis
      apt: name=redis-server update_cache=yes

    - name: Create user redis
      user: name=redis system=yes home=/var/lib/redis shell=/bin/false

    - name: Start Redis
      service: name=redis-server state=started

    - name: install node dependencies
      npm: name=bower global=yes 

    - name: install node dependencies
      npm: name=grunt-cli global=yes 

    - name: install node dependencies
      npm: path={{project_dir}}

    - name: create new role 
      sudo_user: postgres
      postgresql_user: name=multiad password=multiad

    - name: create new db
      sudo_user: postgres
      postgresql_db: name=multiad
                     encoding='UTF-8'
                     lc_collate='en_US.utf-8'
                     lc_ctype='en_US.utf-8'
                     template='template0'
                     owner=multiad

    - name: change working directory
      lineinfile: dest=/home/vagrant/.bashrc line='cd {{project_dir}}'

    - name: set default environment
      lineinfile: dest=/home/vagrant/.bashrc line='source /ENV/bin/activate'

  handlers:
    - name: Restart Redis
      service: name=redis state=restarted
